version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    ## Cannot create namespace xx.xx in multi-document transaction.
    ## mongo 4.2 does not support create document before create collection.
    ## mongo 4.2 needs manualy create collection.
    # image: mongo:4.2.14
    command: mongod --replSet rs0 --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./data/mongo:/data/db

# docker-compose exec mongo mongo --port 27018 --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27018'}]});"